import {
  Archive,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  AtSign,
  Baby,
  Bell,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  Camera,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Coins,
  Copy,
  Crown,
  Delete,
  Download,
  Egg,
  Eye,
  EyeOff,
  FileSpreadsheet,
  FileText,
  Fingerprint,
  Flag,
  Flame,
  Gem,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  House,
  Image as ImageIcon,
  Languages,
  Laptop,
  Lightbulb,
  Link2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MessageCircle,
  Minus,
  Moon,
  Pause,
  PawPrint,
  PenLine,
  Percent,
  Phone,
  PiggyBank,
  Plane,
  Play,
  Plus,
  QrCode,
  ReceiptText,
  Repeat,
  ScanLine,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Sun,
  Target,
  Trash2,
  TreePalm,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlink,
  User,
  UserPen,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react-native';

const ICONS = {
  // UI
  add: Plus,
  alert: CircleAlert,
  at: AtSign,
  back: ChevronLeft,
  backspace: Delete,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  'check-circle': CircleCheck,
  chevron: ChevronRight,
  'chevron-down': ChevronDown,
  clock: Clock,
  close: X,
  coins: Coins,
  copy: Copy,
  deposit: ArrowDownLeft,
  edit: PenLine,
  eye: Eye,
  'eye-off': EyeOff,
  flag: Flag,
  heart: Heart,
  idea: Lightbulb,
  image: ImageIcon,
  language: Languages,
  link: Link2,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  moon: Moon,
  phone: Phone,
  piggy: PiggyBank,
  qr: QrCode,
  receipt: ReceiptText,
  settings: Settings,
  share: Share2,
  smartphone: Smartphone,
  sun: Sun,
  target: Target,
  switch: ArrowLeftRight,
  trash: Trash2,
  'trend-down': TrendingDown,
  'trend-up': TrendingUp,
  unlink: Unlink,
  user: User,
  'user-edit': UserPen,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  withdraw: ArrowUpRight,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  archive: Archive,
  bell: Bell,
  'calendar-clock': CalendarClock,
  crown: Crown,
  download: Download,
  egg: Egg,
  'file-csv': FileSpreadsheet,
  'file-pdf': FileText,
  fingerprint: Fingerprint,
  flame: Flame,
  message: MessageCircle,
  minus: Minus,
  pause: Pause,
  percent: Percent,
  play: Play,
  repeat: Repeat,
  scan: ScanLine,
  send: Send,
  star: Star,
  trophy: Trophy,
  // Goal categories
  plane: Plane,
  home: House,
  car: CarFront,
  gem: Gem,
  shield: ShieldCheck,
  graduation: GraduationCap,
  paw: PawPrint,
  baby: Baby,
  gift: Gift,
  palm: TreePalm,
  laptop: Laptop,
  sofa: Sofa,
  health: HeartPulse,
  food: UtensilsCrossed,
  briefcase: BriefcaseBusiness,
  sparkles: Sparkles,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const GOAL_ICON_NAMES = [
  'plane',
  'home',
  'car',
  'gem',
  'shield',
  'graduation',
  'paw',
  'baby',
  'gift',
  'palm',
  'laptop',
  'sofa',
  'health',
  'food',
  'briefcase',
  'sparkles',
] as const satisfies readonly IconName[];

export type GoalIconName = (typeof GOAL_ICON_NAMES)[number];

export function Icon({ name, size = 22, color, strokeWidth = 2 }: { name: IconName | string; size?: number; color: string; strokeWidth?: number }) {
  const Glyph = ICONS[name as IconName] ?? Sparkles;
  return <Glyph size={size} color={color} strokeWidth={strokeWidth} />;
}
