-- ============================================================================
-- Nido · migration 006: amount limits and friendlier sign-up checks
-- Run after 005_family_codes_currency.sql (SQL Editor → New query → paste → Run).
--
-- * Contributions, withdrawal requests and automatic contributions must be between a minimum
--   and a maximum that depend on the nest's currency (a withdrawal may take the whole remaining
--   balance even if it's below the minimum). Same values as `src/utils/limits.ts`.
-- * Sign-up checks ignore the username/document of an unconfirmed account with the same email,
--   so retrying a sign-up whose confirmation email never arrived works (Supabase resends it).
-- ============================================================================

create or replace function public.amount_limits(p_currency text, out min_amount numeric, out max_amount numeric)
language sql immutable as $$
  select
    case p_currency when 'USD' then 1 when 'EUR' then 1 when 'COP' then 2000 when 'ARS' then 500
      when 'CLP' then 500 when 'PEN' then 2 when 'GTQ' then 5 else 10 end,
    case p_currency when 'USD' then 25000 when 'EUR' then 25000 when 'COP' then 100000000 when 'ARS' then 25000000
      when 'CLP' then 25000000 when 'PEN' then 100000 when 'GTQ' then 200000 else 500000 end;
$$;

create or replace function public.check_amount(p_couple uuid, p_amount numeric, p_allow_below numeric default null)
returns void language plpgsql stable security definer set search_path = public as $$
declare
  lim record;
begin
  select l.* into lim from couples c, amount_limits(c.currency) l where c.id = p_couple;
  if p_amount > lim.max_amount then raise exception 'amount_too_large'; end if;
  if p_amount < lim.min_amount and (p_allow_below is null or p_amount <> p_allow_below) then raise exception 'amount_too_small'; end if;
end;
$$;

-- Deposits typed by people. Refunds and approved withdrawals are generated by the system, and
-- automatic contributions were checked when the rule was created (a later currency change may
-- convert them below the new minimum).
create or replace function public.enforce_deposit_limits()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.type = 'deposit' and not new.refund and new.recurring_id is null then perform check_amount(new.couple_id, new.amount); end if;
  return new;
end;
$$;
drop trigger if exists transactions_amount_limits on public.transactions;
create trigger transactions_amount_limits before insert on public.transactions
  for each row execute function public.enforce_deposit_limits();

-- Withdrawal requests: within limits, or exactly the whole remaining balance of that goal/fund.
create or replace function public.enforce_request_limits()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.kind = 'withdraw' then perform check_amount(new.couple_id, new.amount, nest_balance(new.couple_id, false, new.goal_id)); end if;
  return new;
end;
$$;
drop trigger if exists approval_requests_amount_limits on public.approval_requests;
create trigger approval_requests_amount_limits before insert on public.approval_requests
  for each row execute function public.enforce_request_limits();

create or replace function public.enforce_recurring_limits()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform check_amount(new.couple_id, new.amount);
  return new;
end;
$$;
drop trigger if exists recurring_amount_limits on public.recurring_rules;
create trigger recurring_amount_limits before insert on public.recurring_rules
  for each row execute function public.enforce_recurring_limits();

revoke execute on function public.check_amount(uuid, numeric, numeric) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Sign-up checks aware of a pending (unconfirmed) account with the same email
-- ---------------------------------------------------------------------------

-- True when `p_email` has an account that was never confirmed (its data can be reused on retry).
create or replace function public.is_pending_email(p_user uuid, p_email text)
returns boolean language sql stable security definer set search_path = public, auth as $$
  select exists (
    select 1 from auth.users u
    where u.id = p_user and lower(u.email) = lower(trim(coalesce(p_email, ''))) and u.email_confirmed_at is null
  );
$$;

create or replace function public.username_available(p_username text, p_email text)
returns boolean language sql stable security definer set search_path = public as $$
  select not exists (
    select 1 from profiles p where p.username = lower(trim(p_username)) and not is_pending_email(p.id, p_email)
  );
$$;

create or replace function public.document_available(p_country text, p_type text, p_number text, p_email text)
returns boolean language sql stable security definer set search_path = public as $$
  select not exists (
    select 1 from profile_private pp
    where pp.document_country = p_country and pp.document_type = p_type and pp.document_number = upper(trim(p_number))
      and not is_pending_email(pp.id, p_email)
  );
$$;

-- Whether the email already has a confirmed account (then the person should sign in instead).
create or replace function public.email_registered(p_email text)
returns boolean language sql stable security definer set search_path = public, auth as $$
  select exists (select 1 from auth.users where lower(email) = lower(trim(p_email)) and email_confirmed_at is not null);
$$;

revoke execute on function public.is_pending_email(uuid, text) from public, anon, authenticated;
grant execute on function public.username_available(text, text), public.document_available(text, text, text, text), public.email_registered(text)
  to anon, authenticated;
